### PR TITLE
Add support for submitting forms to a new tab

### LINKED ISSUE #29: Improve detection of form submission into new tab
[As decribed here](https://github.com/swup/forms-plugin/pull/26#discussion_r958422825), we need to find a way to detect if a form submission was sent to a new tab. 

This behavior is natively supported by Chrome and Safari on MAC by holding down the `Meta` (command) key and by Edge on Windows by holding the `Control` (ctrl) key. There exists an [extension for FireFox](https://github.com/mikeconley/tab-submit-basic) that makes the same thing possible.

My first idea would be to use [`document.visibiltyState`](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState). Opening a new tab should hide the current tab, right? I will test this out.

### PR DESCRIPTION
**Pull request by hirasso**
Allows Chrome and Safari to submit forms to a new tab. Causes FireFox to do a hard browser reload on submit if either `command` or `control` are being pressed while submitting. Fixes #29

### CODE REVIEW

**Comment by daun** [comment]
Looks promising! Will need to wrap my head around this and give it a spin.

Why would a cmd-submit force a hard reload in Firefox? There's nothing in the code I can see that's causing that.

**Comment by hirasso** [comment]
The script won't execute `event.preventDefault` anymore, if one of the special keys is down, causing FireFox to just submit the form and swup to ignore it. Basically the same behavior as pressing `control` on Chrome. The form will just submit natively.

**Comment by daun** [comment]
> The script won't execute `event.preventDefault` anymore, if one of the special keys is down, causing FireFox to just submit the form and swup to ignore it. Basically the same behavior as pressing `control` on Chrome. The form will just submit natively.

I see. That doesn't sound optimal, but since Firefox users aren't used to cmd-clicking submit buttons, it should be fine.

**Comment by daun** [comment]
Another question: the new tabs all open in the background for me. That would not fire the `visibilitychanged` event, I guess?

**Comment by daun** [comment]
On your test site, the console log is empty. I assume that's because of the tabs opening in the background.

**Comment by hirasso** [comment]
> I see. That doesn't sound optimal, but since Firefox users aren't used to cmd-clicking submit buttons, it should be fine.

I would say this is the cleanest possible approach.

> On your test site, the console log is empty. I assume that's because of the tabs opening in the background.

Ah damn, I have a plugin running that opens my tabs in the front! Completely had forgotten about it 😅 
...I have a bad feeling about the event `openFormSubmitInNewTab`, anyways – we should probably remove it, it never really worked ever, anyways.

**Comment by hirasso** [comment]
...and it wouldn't be fired in FireFox, so relying on it would be a bad idea. Should we remove it then?

**Comment by daun** [comment]
I agree, let's remove the new-tab event. Nobody was relying on it if it was broken to begin with. If we ever figure it out, we can add it back.

However, how do we make sure to detect if the form was actually submitted in the new tab? The worst that could happen is that we don't submit it in swup, when it wasn't opened by the browser, either.

**Comment by daun** [comment]
One idea could be to prevent the submission, set `target="_blank"` on the form, re-submit via JS, and remove the `target` attr again. That way, we'd add the cmd-click behavior to Firefox. That's IMO better than risking forms that don't submit at all.

**Comment by hirasso** [comment]
> I agree, let's remove the new-tab event. Nobody was relying on it if it was broken to begin with. If we ever figure it out, we can add it back.

👍

> However, how do we make sure to detect if the form was actually submitted in the new tab? The worst that could happen is that we don't submit it in swup, when it wasn't opened by the browser, either.

We are not preventing the browser from submitting the form if one of the special keys is pressed. So the browser will just submit the form as it would do with any other form, either to a new Tab in supporting browsers or to the same window in FireFox. I don't see a problem there.

**Comment by hirasso** [comment]
> One idea could be to prevent the submission, set target="_blank" on the form, re-submit via JS, and remove the target attr again. That way, we'd add the cmd-click behavior to Firefox. That's IMO better than risking forms that don't submit at all.

Crazy idea! It feels like overkill to me, though. Let's just give the form's control back to the browser if one of the special keys is down.

**Comment by daun** [comment]
> We are not preventing the browser from submitting the form if one of the special keys is pressed. So the browser will just submit the form as it would do with any other form, either to a new Tab in supporting browsers or to the same window in FireFox. I don't see a problem there.

Seems like I hadn't completely wrapped my head around it, after all. Sounds good.

**Comment by daun** [comment]
One more thing: can you currently submit the form by cmd+enter when focus is inside the input? Just enter works fine, but cmd+enter doesn't do anything. Edit: Safari works, Chrome doesn't.

**Comment by hirasso** [comment]
Seems like this is not intended: https://superuser.com/questions/693689/chrome-submit-form-in-new-tab-with-keyboard
...but it points us to Opera using the Shift key and Chrome using `Shift+Enter` for submitting forms to a new window! So I will add the `Shift` key to the `specialKeys`

**Comment by hirasso** [comment]
Just tested `command+Enter` on Safari: It works, so the plugin is not interfering, it just isn't implemented in chrome. Crazy how inconsistent this is, feels like css in 2006 🤯

**Comment by hirasso** [comment]
Updated the test site with support for `Shift+Enter`

**Comment by hirasso** [comment]
I just realized that [this use case](https://github.com/swup/forms-plugin/issues/27) would break with the current implementation, if a user would submit a form to a new tab / hard page load, since the `submitForm` event would not be fired in that case. And even if the event would be fired in all cases, any attached listeners would not be executed anymore if the page would have been hard reloaded. Happy to talk you through it if you want ;)

**Comment by hirasso** [comment]
...also, intuitively, this should prevent swup from submitting the form:

```js
swup.on('submitForm', e => {
  e.preventDefault();
});
```
Could be easily implemented, but maybe we will break some people's code? Anyhow, these changes are worth a major version, anyways...

**Comment by daun** [comment]
> Just tested command+Enter on Safari: It works, so the plugin is not interfering, it just isn't implemented in chrome. Crazy how inconsistent this is, feels like css in 2006 🤯

Wow, that's insane. Interestingly, GitHub seems to have implemented this on their own in the global search bar.

> I just realized that https://github.com/swup/forms-plugin/issues/27 would break with the current implementation, if a user would submit a form to a new tab / hard page load, since the submitForm event would not be fired in that case. And even if the event would be fired in all cases, any attached listeners would not be executed anymore if the page would have been hard reloaded.

The normal submit event even fires for submissions to a new tab; so ideally we'd keep this behavior similar in swup.

> ...also, intuitively, this should prevent swup from submitting the form: `e.preventDefault()`

This ties into the revamp of the plugin/event system I have in mind, being able to cancel/prevent any events, native as well as swup, to give more control to users as well as plugins. In the meantime, I think cancelling the submit event in the capture phase should work fine.

> Happy to talk you through it if you want ;)

Sure, let's include that in the docket for tomorrow.

**Comment by hirasso** [comment]
We will actually have to implement this cross-browser, if we want to keep all uses of `submitForm` working for consumers of swup. I will look into this.

**Comment by hirasso** [comment]
This is fun! 😃 I was able to solve the cross-browser issues by using the capture phase in the delegate call, [as described here](https://github.com/fregante/delegate-it#with-listener-options). New features:

- Submissions to new tabs now work consistent cross-browser (if either `control` or `command` is pressed)
- Submissions to new windows as well (if `shift` is pressed)
- `submitForm` is now being fired before all that happens
- Swup will now respect `preventDefault` and fire a new event `submitFormPrevented` if that happens.

**Comment by daun** [comment]
Fantastic ☃️ I'll read it over, but this should get us over the finish line. That way we could probably bring back the `newTab` event as well. I'd suggest splitting it into a `beforeFormSubmit` handler and an `onFormSubmit` handler so we can reset the target attribute after the submission. Some people might be setting that on their forms, and we'd need to reset it properly.

**Comment by hirasso** [comment]
That's all very good thoughts. Will take care of it tomorrow.

**Review by daun — APPROVED** [review]

**Pull request merged**
